FROM jenkins/jenkins:lts
MAINTAINER Joel Fogue <joel.fogue@quickpivot.com>

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

#RUN sudo mkdir -p /var/jenkins_home
#RUN sudo chown -R 1000:1000 /var/jenkins_home
